### ISSUE TITLE
Won't Load

### ISSUE THREAD

**Issue by TooVeryIcey** [NeumimTo/NT-RPG#11]
I have installed the plugin int the mods folder, however on reboot, it does not seem to load

**Comment by NeumimTo** [comment]
Today i released a new version - 1.0.4 you can grab it here https://github.com/NeumimTo/NT-RPG/releases/tag/1.0.4
For more detailed info how to install this plugin see https://github.com/NeumimTo/NT-RPG/wiki/Administrators-guide#requirements - make sure to install its dependency nt-core,
If it wont load again please provide a server log.
