### ISSUE TITLE
Entity problem

### ISSUE THREAD

**Issue by struters** [NeumimTo/NT-RPG#13]
Hi, when the server load, it seems this error occurs repeatedly.

`CONSOLE: thread/ERROR] [Sponge]: Could not pass DestructEntityEvent$Death$Impl to Plugin{id=nt-rpg, name=NT-Rpg, version=1.0.0, source=/home/Minecraft/McMyAdmin/Minecraft/mods/NT-RPG-1.0.2-shaded.jar}`

Sponge Forge version 1.10.2-2185

regards

**Comment by NeumimTo** [comment]
im closing this issue, if problems remain with the new version let me know.
