### ISSUE TITLE
Include example .conf files

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#34]
Another idea i have is to include some example config files with comments, examples below:
https://pastebin.com/ikC9sT6d
https://pastebin.com/Ej31Rez1

Kind of give first time users a feel for how the code flow is supposed to be, not that i know if mine is even correct.. lol

What do you think? I'll handle making the config file and adding comments (with your help to get everything working) so it doesn't distract you from the real work :)

Mildly related: Are the .conf files written in standard javascript? I.E can i use // to comment a line or /* */ to comment multiple?

**Comment by hellbringer616** [comment]
Update:
https://pastebin.com/KGtv9shf
Break out of comments using standard Javascript formatting; will change if not acceptable in the config.

**Comment by NeumimTo** [comment]
In fact thats just hocon formatting, not javascript. 

Ill create a separate github repository for config examples and other assets i have.

**Comment by hellbringer616** [comment]
Please link me if you wouldn't mind.
Updated Notepadqq (the linux Notepad++) default language to JSON; not identical but it has the syntax highlighting i desire :P

**Comment by NeumimTo** [comment]
https://github.com/NeumimTo/NT-RPG-Configs-And-Assets 
Over time ill put here examples complex examples.
