### ISSUE TITLE
Arrow fired bows do not damage mobs

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#37]
Version: Dev build for Sponge API 7.1 Build Date 3/14/18

[Issue]
When firing an arrow at a mob the arrow seems to deflect back at the player and deals no damage to the mob.
No console errors produced in Sponge Server Window.

[CONFIGURATION FILES]
Class.conf: https://pastebin.com/1xf7Dedy
SkillTree.conf: https://pastebin.com/heSGPEtY
race.conf: https://pastebin.com/cmA2E3R3

**Comment by NeumimTo** [comment]
You are missing data in the section projectiledamage

**Comment by hellbringer616** [comment]
Explains why punching things with a bow kills it instantly.. (: 
I have
```
ProjectileDamage: {
  TIPPED_ARROW: 15
}
```
defined in the race.conf; it was the default one in your stock config; do i need it in both race and class?

**Comment by NeumimTo** [comment]
Thats completly up to you if you want to define it in both race and classes. The final damage will be the higher one.
