### ISSUE TITLE
[MINOR] SkillTree GUI naming incorrect

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#40]
**Version:** 1.0.11-SNAPSHOT #3

**[issue]:**
In the SkillTree inventory GUI the "Left" and "Down" titles are inversed; so the button titled "Down" moves the GUI Left and the button titled "Left" moves the GUI down.

**Comment by NeumimTo** [comment]
Its just wrong initial configuration. Right now you can fix it by chaning a configuration value
Look into plugin config and search for node SKILLTREE_BUTTON_CONTROLLS

**Comment by hellbringer616** [comment]
I'll check that out after work. Thanks!
