### ISSUE TITLE
DefaultManaRegen does not function

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#42]
Dev build: eafb351
SpongeForge API 7.1 

**[ISSUE:]**
When DefaultManaRegen is set under race or class mana does not regenerate.

Console does not seem to display errors.

**[CONFIG:]**
Race.conf: https://pastebin.com/tuRR1CzL

**Comment by NeumimTo** [comment]
In this build i already implemented a new effect system which changes how the effects works.

Change effect section to be type of object rather than list

    Effects: {
      DefaultManaRegen: {}
    }

Also make sure a player has a class or a race which is having these properties with a value greather than 0:

    max_mana
    mana_regen
