### ISSUE TITLE
Support any item from mods

### ISSUE THREAD

**Issue by NeumimTo** [NeumimTo/NT-RPG#45]
Currently its not possible to easily, for common users,  add new types of weapons into the plugin ecosystem.

Change entire concept of ItemGroups.conf
- generate required classes at runtime via asm/or some stupidly overcomplicated object structure based on simple configuration. 

conf example
  properties: [
     prop1, 
     prop2
  ]
  weaponGroups: [
    blunt: {
       items: [  "somemod:someitem", "vanilaitem;damage" ]
       onMeeleDamage: "(prop0 + prop1) * prop2"
    }
    blades...
    polearms...
  ]

**Comment by hellbringer616** [comment]
This feature would be wonderful for me.

**Comment by NeumimTo** [comment]
resolved in snapshot 13
