### ISSUE TITLE
REGRESSION: Character state not recalled on load

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#52]
When logging in players must always execute /char switch {charactername} to play as their last used character.

The setting (which i cannot recall as i'm not at my PC atm) to recall last used character on login is set to true in the config.

This has been a bug for a while and i just haven't reported it.. :)

**Comment by hellbringer616** [comment]
UPDATE:
Character state functions in `SNAPSHOT 3`
Breaks in `SNAPSHOT 4`

**Comment by hellbringer616** [comment]
Well i am at a serious loss.... it worked when i loaded up snapshot 3.

Now it's busted again; will test tomorrow as i'm too tied to continue....

**Comment by NeumimTo** [comment]
Current system is a little bit retarded i admit. 

There are two events in sponge after player logs in.  
FIrst is a ClientConnectionEvent.Auth which loads stuff from database. 
After small time delay another event ClientConnectionEvent.Join is called. If the data have been loaded the player is autoassigned to the last character. 

 Fixing this should be quite easy.
