### ISSUE TITLE
Damage output incorrect for Pickaxes

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#53]
Damage output for weapons is incorrect with my config for hoes, spades, and especially Pickaxes.

## **To reproduce perform the following:**
1.) in the settings config set `"WEAPON_MERGE_STRATEGY": ` to `1`

2.) Download the following configs and place them in the Race and Class folders:
https://pastebin.com/acFUm05w
https://pastebin.com/i8xQML23
_Skills have not been made yet so they are not included_

**_3.)a Damage bug:_**
Put all diamond tools in the hot bar and create a character with the downloaded class/race combination; strike any enemy to view damage output; it will be incorrect:
Axes and Swords seem to be correct; have not done math to verify.
Spades and Hoes do 2.5 damage (Correct)
Pickaxes do 1 damage (Should be 2.5)

**_3.)b Armor bug:_**
Attempt to equip diamond armor; when leaving the inventory it will be dropped on the floor.

**Comment by hellbringer616** [comment]
Hoes and spades not effected; i thought the config was the one that added 3 to all diamond weapons haha.. :)

**Comment by NeumimTo** [comment]
Could you also upload itemgroups.conf

**Comment by hellbringer616** [comment]
Ask and you shall receive!
https://pastebin.com/Mkf98TsY

Checked for the  Diamond Pickaxe and it is infact in the list as you'll see.

No armors though so perhaps that is the issue there; when you changed the code to accept moded gear do you think the auto add of default armors was affected? i remember it used to work back in snapshot 2

**Comment by hellbringer616** [comment]
UPDATE:
`ALLOWEDARMOR: [
]` only functions when inside of a class; not a race; and that is the source of my bug for Armor

**Comment by NeumimTo** [comment]
This should be fixed, closing it.
