### ISSUE TITLE
Console log spammed on right click event

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#57]
API: 1.11-SNAPSHOT 13
When right clicking i am getting a spammed console log: https://pastebin.com/wPSpY3Jj

Does not appear to effect anything so i'd set this to a low priory bug (makes debugging annoying is about it)

**Comment by NeumimTo** [comment]
I could not reproduce.  it might happen when the plugin is not able to read some config file due to eg wrong formatting.
