### ISSUE TITLE
Request: Define items to cast skills on click.

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#59]
I'd like to hotbar skills (mmo style) so my plays can cast on click if you will.

Would it be possible to add a .conf file that runs a command when left clicking with a certain item in hand?
I'm thinking i could make a custom item using optifine and then define it there to have my players cast it.

my players rejected the idea of combos with the mouse buttons.. alternatively, if we could add a modifier key that once pressed and you enter the combo it would trigger. They'd be fine with that

**Comment by NeumimTo** [comment]
Theres a command already which binds skills to itemstack.  Currently this feature is broken due to inventory refactor.  its on my todo list

**Comment by NeumimTo** [comment]
Its not really possible to listen on server for any other key Press than rmb lmb q shift and e.  only sollution would be mods but ill leave this crazyness for others

**Comment by hellbringer616** [comment]
If I can define with an item stack I'll just use optifine magic to make items that cast skills.
