### ISSUE TITLE
"Error executing skill: Null" when casting skills

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#61]
When casting Icebolt and Empathy the error "Error executing skill: Null" is displayed in chat. eith Emathy nothing happens, with Icebolt a snowball is thrown; and nothing happens.

pastebin is down i guess so i'll have to paste the log later.

**Comment by hellbringer616** [comment]
https://drive.google.com/file/d/1ndj-t6lbqip5Anm_k5mJZhQfcABNwzKr/view?usp=sharing
log file

**Comment by NeumimTo** [comment]
Ill need your configuration for these skills from your skilltree

**Comment by hellbringer616** [comment]
https://github.com/hellbringer616/Strix_RPG/blob/master/Skilltrees/MageiaSK.conf
There you go big guy :)
