### ISSUE TITLE
Fireball does inconsistent damage

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#62]
When casting fireball the damage is either 1/10th of what it should be (0.2 instead of 2) or 10 times the amount (20 instead of 2)

Pastebin is currently down so i'll have to post the log later.

**Comment by NeumimTo** [comment]
fireball deals a fire damage, check your settings in class/races files for fire_damage_mult and/or fire_damage_resistance

**Comment by hellbringer616** [comment]
Class.conf: 	
fire_damage_bonus_mult: 1.0
fire_damage_protection_mult: 1.0
Race.conf
fire_damage_bonus_mult: 0.01 (should be an 0.1)
fire_damage_protection_mult: 0.2

Remember i use the weaponmerge 1 so it should be the cum (1.01 in this case)

**Comment by hellbringer616** [comment]
Ohhhhh.. Makes sense that would apply to weapons only... being "Weapon_MERGE_STRATEGY" lol....

Hmm do creepers have fire resistance? first mob i killed was a creeper; did 0.1999999956 damage each hit. second mob was a spider; did 20

**Comment by hellbringer616** [comment]
https://drive.google.com/file/d/1ndj-t6lbqip5Anm_k5mJZhQfcABNwzKr/view?usp=sharing
Since pastbin doesn't work; here is the log file.

**Comment by NeumimTo** [comment]
No, all mobs have default resistances. if property ends with _mult then default value is 1 otherwise 0.

Could you try to run the skill via /nadmin skill fireball command?

**Comment by NeumimTo** [comment]
I cannot reproduce with your configurations. Is it possible that you have another plugin, or mod, which is affecting damage in any way?
