### ISSUE TITLE
Gaining XP with CustomNPC quests

### ISSUE THREAD

**Issue by DixxyDix** [NeumimTo/NT-RPG#72]
Can you please do something to get experiences from any custom NPC quests ? Like killing mobs, gathering resources, location quests etc. 

Its like you create a dialog with an NPC, by an HUD and you can like give options to the quest, like how much experience you get (its the minecraft experience system) and stuff like that.

https://youtu.be/LjurA9VKCk8?t=360

This is a timestamp of a video about quest on CustomNPC

Thanks !

**Comment by NeumimTo** [comment]
https://github.com/Sponge-RPG-dev/NT-RPG-Mods-Bridge
With this plugin you can configure:
- whenever the player will gain experiences after killing npc 
- whenever the player will gain experiences after completing a quest

**Comment by NeumimTo** [comment]
@DixxyDix if you need anything more specific, please create issue in the mods-bridge repository
