### ISSUE TITLE
Adding more characters per permission group for plugins

### ISSUE THREAD

**Issue by marines4ever** [NeumimTo/NT-RPG#74]
Maybe adding additional ways to add more character slots.

Say Default starts with 3 characters max
Members get 5 characters max
and option of adding some more ranks as well maybe 3-5 options

**Comment by NeumimTo** [comment]
Would it be fine for your use-case if i create a permission node eg.:
`ntrpg.override.character-limit.<an-integer>` ? 
Where the integer is variable, which tells the plugin, how many characters, may the playing create. If the player has no such permission the plugin will check the global config value
