### ISSUE TITLE
Make class/race system more abstract

### ISSUE THREAD

**Issue by GlassSpirit** [NeumimTo/NT-RPG#77]
I suggest you to make classes/races more abstract and use “groups” system. This would allow to make custom “class groups” as professions, star constellation, etc. with racial skills, percs.
For example check SkillApi plugin for spigot https://github.com/Eniripsa96/SkillAPI

**Comment by NeumimTo** [comment]
Hi, 
Thanks for feedback. 

Class professions:
This is on my todo list, right now you can have exactly one class (lets call it primary class) and one race. in future you will be able to configure the class system which allows you to have an unlimited amount of classes at once. 
Parts of the plugin are ready for this change parts are not. It might make it eventually into 1.0.12 release.

Racial skills: 
This feature will be completed during 1.0.12 development. 
My plans are: 
  - No skill tree, racial skill points, or complex skill relations 
  - You only define level for each skill. Once player reaches that level on its primary class it automatically unlocks that one specific racial skill

star constellation/percs
I have no idea what those are, what do you would like to have.
I dont know much about the skillapi. its "full" version is behind the paywall so i never really tested it out.

**Comment by GlassSpirit** [comment]
I mean you can make some “class groups” system, which by default contain “rpg class” and “race” group and treat them almost the same way (different level for each group, skills, additively stacking stats). By doing so admins and devs would be able to define custom “class groups” as “job”, which contains for example “miner”, “herbalist” and “achemist”, class group “devotion”, which contains some gods linked with server lore and giving constant buff and so on.
I know it is very fundamental change to make, but it will make system much more flexible.
Also, if future class system would allow to have unlimited amount of classes at once, why not tread the “race” as just another class?

**Comment by NeumimTo** [comment]
The main goal of these "class groups" would be to simplify character creation processor for players? 
In that case you can achieve this already in-game via commandblocks. 

All buttons in all inventory menus just invoke other commands under the hood.
/char set <race/class> <name> or theres also /nadmin set 
The /char command will fail if the player do not meet class' requirements (such as permission, or race), nadmin command bypasses all restrictions.

If you think about 'star constellation' as the ingame mechanic from eg,: TES Oblivion - it will be doable via secondary classes. 

When i designed race system i thought about racial abilities only as wow's racial traits for example. I just wanted them to be different from classes. Allowing race to level up should not be some large breaking change for me.

**Comment by NeumimTo** [comment]
I tried to sum up some stuff here: https://github.com/NeumimTo/NT-RPG/issues/78

**Comment by GlassSpirit** [comment]
Yeah, this is almost what I wanted to say, thank you for reply)
